version: "3"
services:
  db:
    image: postgres
    container_name: contact-manager-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections'=500"
    env_file: .env
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    env_file:
      - .env

    volumes:
      - app_storage:/rails/data
    depends_on:
      - db

volumes:
  postgres_data: {}
  app_storage: {}

networks:
  contact_manager: {}
